export const TEXTURE_SIZE = 3000;
export const SCALE = 3;
export const BOUNDS = [(-TEXTURE_SIZE * SCALE) / 2, (TEXTURE_SIZE * SCALE) / 2];
export const BULLET_SPEED = 0.5;
export const BULLET_FIRE_RATE = 50; // 1 bullet every 50ms
export const ENEMY_SPEED = 0.24;
export const FIXED_TIMESTEP = (1 / 60) * 1000; // 60fps (in ms)
export const GAP = 25;
export const SHIP_SPEED = 1.5;
export const BULLET_DAMAGE = 10;
export const SHIP_COLLISION_DAMAGE = 1;
export const SCORE_PER_KILL = 100;
